### ISSUE TITLE
MQTT connection of venus os disconnects once per minute if grid meter and standard MQTT requests are operated in parallel

### ISSUE THREAD

**Issue by SSonder0815** [mr-manuel/venus-os_dbus-mqtt-grid#17]
I have set up this enhancement to emulate a grid meter. I am sending once per second a new value to the venus os via this connection. When I also used the venus os MQTT for other communication the MQTT connection disconnected once per second for a few seconds. When I removed all the other MQTT connections and only left this one for the emulated grid meter, the disconnection did not happen anymore. There seems to be a conflict when using this MQTT connection in parallel to the other topics. I solved it for the time being by using the modbus protocoll for all the other connections i needed.

**Comment by mr-manuel** [comment]
What does the log say? In the readme it is well documented how to troubleshoot.
