### ISSUE TITLE
Use as load meter

### ISSUE THREAD

**Issue by con0aks** [mr-manuel/venus-os_dbus-mqtt-grid#23]
Hi,

is it possible to use this virtual grid meter as a load meter?

I didn't found the option in the gui to switch the mode.

Thanks in advance :)

**Comment by con0aks** [comment]
When I connect an EM24 to the Venus OS, I can choose the role of the meter as shown in the manual:

<img width="506" alt="Bildschirmfoto 2024-05-29 um 21 54 06" src="https://github.com/mr-manuel/venus-os_dbus-mqtt-grid/assets/99498096/96414cc0-ab58-4f94-aa9d-d3ba15892e11">

**Comment by mr-manuel** [comment]
Can you post a screenshot of the dbus values of that? You can get them via SSH and `dbus-spy`. Else you can write me on Discord.

**Comment by mr-manuel** [comment]
You can select the device type in the `config.ini` from `v0.1.6` on.

https://github.com/mr-manuel/venus-os_dbus-mqtt-grid/blob/3c0ed5672045c26f89211c7e6da3d8a5ced421f8/dbus-mqtt-grid/config.sample.ini#L18-L22

**Comment by con0aks** [comment]
thanks a lot :)
