### ISSUE TITLE
feature request - filter for too high values

### ISSUE THREAD

**Issue by ves1820** [mr-manuel/venus-os_dbus-mqtt-grid#31]
is it possible to add a filter for L1-3 values that are not possible on a normal home connected to the grid with 32A.
i have a tasmota sml mqtt source that sometimes a day gets me 999999W for 2-3 sec.
The batterie than goes unnecessary to 100%.
this would help me a lot

**Comment by mr-manuel** [comment]
Would appreciate a little donation :)
